#!/usr/bin/env bash
set -euo pipefail

# Regenerates .claude/skills, .agents/skills, .github/skills from skills/ and publishes
# the result. Run by .github/workflows/generate-mirrors.yml -- nobody needs to run this
# by hand. Pushes straight to the branch; if that's rejected (e.g. branch protection),
# opens a PR with the regenerated mirrors instead.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

BRANCH="${MIRRORS_BRANCH:-$(git rev-parse --abbrev-ref HEAD)}"
MIRRORS=(.claude/skills .agents/skills .github/skills)
MESSAGE="chore: regenerate vendor mirrors"

"${ROOT_DIR}/scripts/generate-vendor-wrappers.sh"
"${ROOT_DIR}/scripts/check-vendor-skills.sh"

if [[ -z "$(git status --porcelain -- "${MIRRORS[@]}")" ]]; then
  echo "Vendor mirrors already up to date."
  exit 0
fi

git add -A -- "${MIRRORS[@]}"
git commit -m "${MESSAGE}"

if git push origin "HEAD:${BRANCH}"; then
  echo "Pushed regenerated mirrors to ${BRANCH}."
  exit 0
fi

pr_branch="chore/regen-mirrors-$(git rev-parse --short HEAD)"
echo "Direct push to ${BRANCH} rejected -- opening a PR from ${pr_branch} instead."
git push origin "HEAD:refs/heads/${pr_branch}"

body="Regenerated .claude/skills, .agents/skills, .github/skills from skills/. Generated by .github/workflows/generate-mirrors.yml -- merge as-is."
# Labels only exist in some repos; retry without them rather than fail.
if gh pr create --base "${BRANCH}" --head "${pr_branch}" --title "${MESSAGE}" --body "${body}" \
    --label chore --label skip-changelog \
  || gh pr create --base "${BRANCH}" --head "${pr_branch}" --title "${MESSAGE}" --body "${body}"; then
  exit 0
fi

repo_url="${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY:-<owner>/<repo>}"
cat >&2 <<EOF

Could not open the PR. The regenerated mirrors are on branch ${pr_branch}.
Most likely cause: GitHub Actions isn't allowed to create pull requests in this repo
(off by default). Fix once, then re-run this workflow:
  Settings -> Actions -> General -> Workflow permissions ->
  "Allow GitHub Actions to create and approve pull requests"
Or open the PR by hand: ${repo_url}/pull/new/${pr_branch}
EOF
exit 1
